import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import SideNav from "@/components/navigation/side-nav/side-nav";
import TopNav from "@/components/navigation/top-nav/top-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex flex-col md:flex-row size-full overflow-auto bg-muted/40">
            <SideNav />
            <TopNav />
            <div className="size-full md:h-full md:w-max md:flex md:flex-grow">
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
